language: python
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
install:
    - pip install -r requirements.txt
script:
  -  cd farm_management && pytest
services:
  - postgresql