language: python
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install:
    - pip install -r requirements.txt
script:
  -  cd farm_management && pytest 
services:
  - postgresql