# Generated by Django 3.0.7 on 2020-06-15 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('stage', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('production', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('prescription', models.TextField()),
                ('vet', models.CharField(max_length=100)),
                ('date_treated', models.DateTimeField(auto_now_add=True)),
                ('date_observed', models.DateField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='treatment', to='backend.Cow')),
            ],
        ),
        migrations.CreateModel(
            name='Parturation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_served', models.DateField()),
                ('days', models.IntegerField()),
                ('expected_date', models.DateField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='parturation', to='backend.Cow')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('time', models.TimeField()),
                ('rate', models.CharField(max_length=60)),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='feed', to='backend.Cow')),
            ],
        ),
    ]
