# Generated by Django 3.0.7 on 2020-06-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parturation',
            name='days',
        ),
    ]
